package com.faridnia.khoroojyar.data.room

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey
import java.time.LocalDate
import java.time.LocalTime

@Entity(
    tableName = "WorkDayInfos",
    indices = [Index(value = ["day"], unique = true)] // Enforce uniqueness on the 'day' column
)
data class WorkDayInfo(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0, // Default value for autogenerated ID
    val day: LocalDate,
    val firstEnterTime: LocalTime,
    val firstExitTime: LocalTime,
    val secondEnterTime: LocalTime,
    val secondExitTime: LocalTime
)
