name: Android CI

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - uses: actions/checkout@v4

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Step 3: Grant execute permissions to Gradle Wrapper
      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      # Step 4: Build with Gradle
      - name: Build with Gradle
        run: ./gradlew assembleRelease

      # Step 5: Debug APK Directory
      - name: Debug APK Directory
        run: ls -R app/build/outputs/apk/release/

      # Step 6: Upload APK file
      - name: Upload APK file
        uses: actions/upload-artifact@v3
        with:
          name: KhoroojYar-APK
          path: app/build/outputs/apk/release/*.apk
